
spring:
  datasource:
    username: root
    password: '0323'
    url: jdbc:mysql://localhost:3306/db_blog?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8989